### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-dinkum-listener#13]
Compare to `ovos-listener`,  `ovos-dinkum-listener` is missing some libraries.

Here is the list that I'm using to have a functional `ovos-dinkum-listener` with wake word and VAD detection.

```
ovos-stt-plugin-server
ovos-stt-plugin-vosk
ovos-vad-plugin-silero
ovos-ww-plugin-pocketsphinx
ovos-ww-plugin-precise
ovos-ww-plugin-precise-lite
ovos-ww-plugin-vosk
```

**Comment by JarbasAl** [comment]
Since those are all plugins they should not be dragged by default, they are large dependencies that might not be used and would not allow this to be installed in some platforms, an extra for default suggested plugins makes sense

**Comment by goldyfruit** [comment]
> Since those are all plugins they should not be dragged by default, they are large dependencies that might not be used and would not allow this to be installed in some platforms, an extra for default suggested plugins makes sense

By default VAD and wake words are enabled in the configuration which means that a new user, will automatically get errors when starting Dinkum.

**Comment by JarbasAl** [comment]
the user should choose a plugin before launching dinkum, it doesnt work without one we just shouldnt be selecting one for the user

silero wont install in some platforms and is the recommended plugin, but cant be added to requirements

wake words similarly try to use the best plugin whatever is available, we should not bundle one

maybe we can add a [recommended] extras requirement?

**Comment by goldyfruit** [comment]
> the user should choose a plugin before launching dinkum, it doesnt work without one we just shouldnt be selecting one for the user
> 

Yeah but people starts the service directly without changing any configuration because they want to test the solution. Maybe we could prevent the service to start with an INFO/ERROR if no configuration is provided.

> silero wont install in some platforms and is the recommended plugin, but cant be added to requirements

Not required by default, I made a mistake, its `webrtcvad` :p

> maybe we can add a [recommended] extras requirement?

Agree.

**Comment by Bulwagga** [comment]
As a new user, I would be happy with a block flowchart  of how the system worked, with mutually exclusive plugin options associated with, or printed in, each block. 

For example, I'm getting a bit lost in the plugins as I try to build an ovos instance with dinkum-listener. I'm using raspbian on a 3B+ and there is a dependency on glibc 2.33 somewhere under ovos-ww-plugin-precise-lite. Rasbpian is using glibc 2.31 and so I need another solution. I'm busy reading the docs and figuring it out.  Other people might not be so interested in spending their time this way, and I worry we will lose them as potential users.

It would be great if there was a table or flowchart that would list the plugins required to make the different options work.
