### ISSUE TITLE
feature parity

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-dinkum-listener#22]
the mic level meter is not implemented here, use https://github.com/NeonGeckoCom/neon-audio-plugin-noise instead

config auto reload is not implemented https://github.com/OpenVoiceOS/ovos-config/blob/dev/ovos_config/config.py#L258

**Comment by NeonDaniel** [comment]
Is mic level used anywhere? I forgot about it since deprecating the signal directory in Neon.

Unless its necessary, I'd rather not implement it here and leave it to a CLI to integrate with the noise plugin directly

**Comment by JarbasAl** [comment]
only used by the cli i think, users that want it should install the companion Neon plugin  (updates might be needed, i did not test it)
