### ISSUE TITLE
systemd notify: Fail to understand how to properly launch this service through systemd

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-dinkum-listener#42]
I fail to understand how to launch this with systemd as type=notify

Can someone point me to the right way? Or better explain me what, where, how, etc.

**Comment by j1nx** [comment]
To elaborate, this is the systemd wrapper of the "old" voice service;

```
import sdnotify
from ovos_dinkum_listener.ovos_dinkum_listener.client.speech.__main__ import main

n = sdnotify.SystemdNotifier()

def notify_ready():
    n.notify('READY=1')
    print('Startup of Mycroft Voice service complete')

def notify_stopping():
    n.notify('STOPPING=1')
    print('Stopping the Mycroft Voice service')

main(ready_hook=notify_ready, stopping_hook=notify_stopping)
```

So to convert this into;

```
import sdnotify
from ovos_dinkum_listener.service import main

n = sdnotify.SystemdNotifier()

def notify_ready():
    n.notify('READY=1')
    print('Startup of Mycroft Voice service complete')

def notify_stopping():
    n.notify('STOPPING=1')
    print('Stopping the Mycroft Voice service')

main(ready_hook=notify_ready, stopping_hook=notify_stopping)
```
However I do not see which hooks need to be changed to what?

**Comment by emphasize** [comment]
```
import sdnotify
from ovos_dinkum_listener.ovos_dinkum_listener.__main__ import main

main()
```

**Comment by j1nx** [comment]
> ```
> import sdnotify
> from ovos_dinkum_listener.ovos_dinkum_listener.__main__ import main
> 
> main()
> ```
> 
> sdnotify in dinkum listener will report to the service yet i'm not clear atm if all notification types are satisfied (in dinkum)

We need to let systemd know it was started, which is done with sending READY=1 with sdnotify package. I don't see it imported anywhere within Dinkum listener so we still need to do it with the wrapper.

**Comment by builderjer** [comment]
This is my service file. 

https://github.com/OpenVoiceOS/raspbian-ovos/blob/headless/stage-voice/01-voice/files/ovos-dinkum-listener.service

And corresponding file

https://github.com/OpenVoiceOS/raspbian-ovos/blob/headless/stage-voice/01-voice/files/ovos-systemd-dinkum-listener

Don't know if this is correct either

**Comment by j1nx** [comment]
Are you sure the voice service does not get restarted after the timeout of 1 minute?

If this work, I am even more confused. Then somewhere within the dinkum code, it talks to systemd without importing any sdnotify package. ???

**Comment by NeonDaniel** [comment]
This has been working for me in Neon images; I just pass the callback methods to init as usual:
https://github.com/NeonGeckoCom/neon_speech/pull/157/files
https://github.com/NeonGeckoCom/neon-image-recipe/blob/dev/05_neon_core/overlay/usr/libexec/neon-speech.py
https://github.com/NeonGeckoCom/neon-utils/blob/dev/neon_utils/process_utils.py#L40

**Comment by emphasize** [comment]
@jinx you are right, i was somewhat hallucinating and under the impression those were there.

we can work with the default callback handler here and notify from there

```
n = sdnotify.SystemdNotifier()

def on_ready():
    n.notify('READY=1')
    LOG.info('DinkumVoiceService is ready.')

...
```

The mention in the dinkum code (watchdog) is a lambda function that is doing nothing

**Comment by NeonDaniel** [comment]
> To elaborate, this is the systemd wrapper of the "old" voice service;
> 
> ```
> import sdnotify
> from mycroft.client.speech.__main__ import main
> 
> n = sdnotify.SystemdNotifier()
> 
> def notify_ready():
>     n.notify('READY=1')
>     print('Startup of Mycroft Voice service complete')
> 
> def notify_stopping():
>     n.notify('STOPPING=1')
>     print('Stopping the Mycroft Voice service')
> 
> main(ready_hook=notify_ready, stopping_hook=notify_stopping)
> ```
> 
> So to convert this into;
> 
> ```
> import sdnotify
> from ovos_dinkum_listener.ovos_dinkum_listener.__main__ import main
> 
> n = sdnotify.SystemdNotifier()
> 
> def notify_ready():
>     n.notify('READY=1')
>     print('Startup of Mycroft Voice service complete')
> 
> def notify_stopping():
>     n.notify('STOPPING=1')
>     print('Stopping the Mycroft Voice service')
> 
> main(ready_hook=notify_ready, stopping_hook=notify_stopping)
> ```
> 
> However I do not see which hooks need to be changed to what?

OH. I missed the signature change; `ready_hook` and `stopping_hook` aren't the kwargs here, they're `on_ready` and `on_stopping`.

**Comment by emphasize** [comment]
since this 

> @jinx you are right, i was somewhat hallucinating and under the impression those were there.
> 
> we can work with the default callback handler here and notify from there
> 
> ```
> n = sdnotify.SystemdNotifier()
> 
> def on_ready():
>     n.notify('READY=1')
>     LOG.info('DinkumVoiceService is ready.')
> 
> ...
> ```
> 
> The mention in the dinkum code (watchdog) is a lambda function that is doing nothing
> 
> further check: `ovos_utils.process_utils`

to avoi confudion i was reffering to https://github.com/OpenVoiceOS/ovos-dinkum-listener/blob/067a47dce61307704ba6884f8869ec7486182214/ovos_dinkum_listener/service.py#L53

**Comment by builderjer** [comment]
So what should the service file, and exec file be? Similar to listener?
